### ISSUE TITLE
does your steno mode still work

### ISSUE THREAD

**Issue by Kethku** [arleym/model01#1]
I've been trying to get the keyboardio steno mode working but following your firmware as an example and installing plover in geminipr mode doesn't seem to cut it. Plover keeps reporting that the keyboard is disconnected. Clearly i can put plover in keyboard mode, but it would be ideal to be able to leave plover always running and then swap to a plover layer when needed. Any hints? I realize its weird to make an issue but I wasn't sure what the best way to contact you was.

**Comment by Kethku** [comment]
I figured it out moments later. ignore me :)

**Comment by arleym** [comment]
Awesome! I'm curious what the issue was. 

I'm 10x more curious how you're going to learn this - the plan of attack I started with (Anki cards and memorizing word chords) was too steep of a learning curve. I think memorizing by syllable would be amazing.

**Comment by Kethku** [comment]
My issue was that somehow my motherboard has a serial port which is always open and plover had autoselected that port instead of the virtual port that is connected to my keyboardio. A moment of configuration searching fixed it for me 👍. That combined with arduino ide hogging the port meant that things weren't working.

As for learning, thus far my approach is to read through https://sites.google.com/site/ploverdoc/home. The book stresses that mastery of each lesson is completely necessary before moving on. As a result I am planning on spending a relatively small portion of each day working on the current lesson. My goal is to get to the point where I don't have to think about what keys to press. I want fluency in a section before moving on. I completely expect this to take a long time though which is why I am spending a portion of the day systemically.

I have found https://joshuagrams.github.io/steno-jig/learn-plover.html to be super helpful. I am only on the first lesson (we will see how long I last) and the ability to do the tests in order and then randomly is very cool. That combined with the hints mode is really quite cool.

How about you? Have you kept up with it or are you moving on? I am still not sure how practical the skill will be in my day to day life, but the idea is so cool that I couldn't pass up giving it a try.

**Comment by arleym** [comment]
I've seen links to this book, but without a kindle version I lazily was refusing to read it, haha. Really good to know there are lessons, I'll check it out! I temporarily gave up; I want more anecdotal "how I did it / why I did it" stories. I hope to one day be fast enough to live-transcribe sermons at my church.

**Comment by Kethku** [comment]
Hey that's an awesome use case! Just a word of warning though, my understanding is that transcribing is very similar to translating and as such is nearly impossible to comprehend the content while doing it. Comprehension requires engaging with the material and summarizing which is why note taking works, but transcribing takes too many cycles to also engage at the same time. Translators I've talked to say that while they are working they are kind of in a trance like state and couldn't really answer any questions about the content. Still a super worth while skill, but not great if you can only attend on service :)

Unfortunately I do not have a success story yet. I hope to eventually though!

**Comment by arleym** [comment]
Interesting! An unrelated thing I've been learning has been speed listening. I've been pushing myself on listening to podcasts/text-to-speech/audiobooks/videos online at rapid speeds. Sometimes I can listen upwards of 400% - I wonder if that will give me more of this mental bandwidth!
